### ISSUE TITLE
I'm pretty certain that this shouldn't look like that... reinstalling didn't help

### ISSUE THREAD

**Issue by aerospacetgirl** [tw4449-s-MAS-Submods/Custom-Room-Garden-View#3]
Reinstalled the submod few times, verified that everything is as it should be, no help.

![screenshot0001](https://user-images.githubusercontent.com/54122555/145711337-7695eaf1-1c6e-4873-8aca-33a81c3d7d02.png)

Edit: I discovered disabling the "Disable Animations" option solves the bug. The problem is that my computer is crap and well... I would rather have animations off. I hope this problem is solvable.

**Comment by Cdino11** [comment]
Well, what version of the game are you running, do you use one drive, and what platform are you on

**Comment by monikasnerdygirlfriend** [comment]
> 

MAS 12.5 with mod in the version 1.0.2, no One Drive, Windows 10

**Comment by Cdino11** [comment]
Alright thank you, just had to make sure. The problem is on our side, and we are working on it. Thank you for letting us know / letting us know here. The update should be out later today
